TravelHen_Auth_Sln/TravelHen_Auth/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TravelHen_Auth;
using PagedList;
using System.IO;
using Microsoft.AspNet.Identity;

namespace TravelHen_Auth
{
    public class AdminAuthorize : AuthorizeAttribute
    {
        protected override bool AuthorizeCore(HttpContextBase httpContext)
        {
            if (httpContext == null) throw new ArgumentNullException("httpContext");

            // Make sure the user is authenticated.
            if (httpContext.User.Identity.IsAuthenticated == false) return false;

            // Do you own custom stuff here


            Person u = Person.GetByEmail(HttpContext.Current.User.Identity.Name);
            if (u == null) return false;

            // kas on admin kasutaja

            //bool allow = u.IsInRole("Admin");
            bool allow = false;
            if (u.IsInRole("Admin") || u.IsInRole("Buchhalter")) allow = true;
            return allow;
        }
        public class AccountantAuthorize : AuthorizeAttribute
        {
            protected override bool AuthorizeCore(HttpContextBase httpContext)
            {
                if (httpContext == null) throw new ArgumentNullException("httpContext");

                // Make sure the user is authenticated.
                if (httpContext.User.Identity.IsAuthenticated == false) return false;

                // Do you own custom stuff here


                Person u = Person.GetByEmail(HttpContext.Current.User.Identity.Name);
                if (u == null) return false;

                // kas on admin kasutaja
                bool allow = false;
                if (u.IsInRole("Admin") || u.IsInRole("Buchhalter")) allow = true;

                return allow;
            }
        }
    }
    partial class Person
    {
    // tegin andmebaasi static, sest siis on igas meetodis andmebaas kasutada
    static travelhenEntities db = new travelhenEntities();

    //staatiline meetod, mis leiab Personi tema meili alusel



    public static Person GetByEmail(string email)
    => db.Persons.Where(x => x.Email == email).SingleOrDefault();

    public static Person GetByID(int id)
    => db.Persons.Where(x => x.PersonID == id).SingleOrDefault();


        public bool IsInRole(string roleName)
            => this.PersonRoles
                .Select(x => x.Role.RoleName.ToLower())
                .Contains(roleName.ToLower());
     public string FullName => $"{FirstName} {LastName}";

    }

        
}



namespace TravelHen_Auth.Controllers
{
    public class PeopleController : Controller
    {
    
        private travelhenEntities db = new travelhenEntities();


        // GET: People
        public ActionResult Index(string sortOrder, string searchString, int? page)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);

            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Home");

            //kas on meie kasutaja
            Person u = TravelHen_Auth.Person.GetByEmail(User.Identity.Name);
            if (u == null) return RedirectToAction("Index", "Home");

            ViewBag.CurrentUser = u;

            {
                ViewBag.Isikukoodsort = sortOrder == "IK" ? "ik_desc" : "IK";
                ViewBag.FirstNameSort = sortOrder == "firstName" ? "firstName_desc" : "firstName";
                ViewBag.LastNameSort = sortOrder == "lastName" ? "lastName_desc" : "lastName";
                ViewBag.EmailSort = sortOrder == "email" ? "email_desc" : "email";
                ViewBag.DepartmentNameSort = sortOrder == "departmentName" ? "departmentName_desc" : "departmentName";

                var person = from e in db.Persons select e;
                Person CurrentUser = TravelHen_Auth.Person.GetByEmail(HttpContext.User.Identity.Name);
                if (CurrentUser.IsInRole("Buchhalter")/* || CurrentUser.IsInRole("Admin")*/)
                {
                    person = from e in db.Persons select e;
                }
                else if (CurrentUser.IsInRole("Manager"))
                {
                    person = from e in db.Persons
                              where (e.DepartmentID == CurrentUser.DepartmentID)
                              select e;
                }
                else
                {
                    person = from e in db.Persons where (e.PersonID == CurrentUser.PersonID) select e;
                }
                if (!String.IsNullOrEmpty(searchString))
                {
                    person = person.Where(e => e.LastName.Contains(searchString)
                                           || e.FirstName.Contains(searchString)
                                           || e.IK.Contains(searchString)
                                           || e.Email.Contains(searchString)
                                           || e.Department.DepartmentName.Contains(searchString)
                                           );
                }
                switch (sortOrder)
                {
                    case "lastName":
                        person = person.OrderBy(e => e.LastName);
                        break;
                    case "lastName_desc":
                        person = person.OrderByDescending(e => e.LastName);
                        break;
                    case "firstName":
                        person = person.OrderBy(e => e.FirstName);
                        break;
                    case "firstName_desc":
                        person = person.OrderByDescending(e => e.FirstName);
                        break;
                    case "IK":
                        person = person.OrderBy(e => e.IK);
                        break;
                    case "ik_desc":
                        person = person.OrderByDescending(e => e.IK);
                        break;
                    case "email":
                        person = person.OrderBy(e => e.Email);
                        break;
                    case "email_desc":
                        person = person.OrderByDescending(e => e.Email);
                        break;
                    case "departmentName":
                        person = person.OrderBy(e => e.Department.DepartmentName);
                        break;
                    case "departmentName_desc":
                        person = person.OrderByDescending(e => e.Department.DepartmentName);
                        break;

                    default:
                        person = person.OrderBy(e => e.LastName.Contains(searchString));
                        break;
                }
                return View(person.ToList().ToPagedList(pageNumber, pageSize));
            }

            //return View(db.Persons.ToList());
        }

        // GET: People/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.Persons.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }

            //Gert ei saa muuta Martti pilti
            Person martti = db.Persons.Find(5);
            martti.PictureID = 59;
            db.SaveChanges();
            //Askol on ka alati õige pilt
            Person asko = db.Persons.Find(4);
            asko.PictureID = 61;
            db.SaveChanges();
            // siia pistan paar kontrolli:
            // 1. Kas kasutaja on sisse loginud ja meie kasutaja
            // 2. kas kasutaja kuulub õigesse rolli

            // kas on sisse loginud (või häkker)
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Home");

            // kas on meie kasutaja
            Person u = TravelHen_Auth.Person.GetByEmail(User.Identity.Name);
            if (u == null) return RedirectToAction("Index", "Home");
            
            return View(person);


           
        }

        // GET: People/Create
        public ActionResult Create()
        {
            ViewBag.DepartmentID = new SelectList(db.Departments, "DepartmentID", "DepartmentName");
            return View();
        }

        // POST: People/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PersonID,IK,FirstName,LastName,Email,DepartmentID,PictureID")] Person person, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                db.Persons.Add(person);

                //faili lisamine
                if (file != null)
                {
                    if (file.ContentLength > 0)
                    {


                        string[] filenames = file.FileName.Split('\\');
                        File f = new File();
                        f.Filename = filenames[filenames.Length - 1];

                        //if (f.Filetype?.Trim() == "")
                        {
                            string[] filetyps = file.FileName.Split('.');
                            if (filetyps.Length < 2) f.Filetype = "xxx";
                            else f.Filetype = filetyps[filetyps.Length - 1];
                        }
                        f.Contenttype = file.ContentType;

                        if (file.ContentLength > 0)
                        {
                            using (BinaryReader br = new BinaryReader(file.InputStream))
                            {
                                byte[] buff = br.ReadBytes(file.ContentLength);
                                f.Content = buff;
                            }

TravelHen_Auth_Sln/TravelHen_Auth/Views/Shared/BackToTools.cshtml
@Html.ActionLink("Back to Tools", "../Tools/Index", null, new { @class = "fancybutton fancybutton-long" })

TravelHen_Auth_Sln/TravelHen_Auth/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - TravelHen</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @* @Html.ActionLink("TravelHen", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
                <a href="@Url.Action("Index", "Home")" class="navbar-brand">
                    <img src="../../Content/Images/logo.png" title="TravelHen" alt="TravelHenLogo" height="20em" />
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    @{if (TravelHen_Auth.Person.GetByEmail(User.Identity.Name) != null)
                        {
                        <li>@Html.ActionLink("Travels", "Index", "Travels")</li>

                            if ((TravelHen_Auth.Person.GetByEmail(User.Identity.Name).IsInRole("Buchhalter") || TravelHen_Auth.Person.GetByEmail(User.Identity.Name).IsInRole("Admin") || TravelHen_Auth.Person.GetByEmail(User.Identity.Name).IsInRole("Manager")))
                            {
                            <li>@Html.ActionLink("Employees", "Index", "People")</li>
                            }
                            else if (TravelHen_Auth.Person.GetByEmail(User.Identity.Name).IsInRole("Employee"))
                            {
                            <li>@Html.ActionLink("Personal details", $"Details/{ TravelHen_Auth.Person.GetByEmail(User.Identity.Name).PersonID}", "People")</li>
                            }
                            if ((TravelHen_Auth.Person.GetByEmail(User.Identity.Name).IsInRole("Buchhalter") || TravelHen_Auth.Person.GetByEmail(User.Identity.Name).IsInRole("Admin")))
                            {
                            <li>
                                <a data-toggle="dropdown" href="#">Administrative tools<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>@Html.ActionLink("Tools", "Index", "Tools")</li>
                                    <li>@Html.ActionLink("Travel Expenses", "Index", "TravelExpens")</li>
                                    <li>@Html.ActionLink("Files", "Index", "Files")</li>
                                    <li>@Html.ActionLink("Logs", "Index", "Logs")</li>
                                </ul>
                            </li>
                                

                                @*<li>@Html.ActionLink("Tools", "Index", "Tools")</li>
                                <li>@Html.ActionLink("Travel Expenses", "Index", "TravelExpens")</li>
                                <li>@Html.ActionLink("Files", "Index", "Files")</li>
                                <li>@Html.ActionLink("Logs", "Index", "Logs")</li>*@
                            }
                        }
                        }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - TravelHen™  <a href="https://chickenonaraft.com" target="_blank">🐔</a></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>