TravelHen_Auth_Sln/TravelHen_Auth/Controllers/FilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TravelHen_Auth;
using System.IO;

namespace TravelHen_Auth.Controllers
{
    [Authorize]
    public class FilesController : Controller
    {
        private travelhenEntities db = new travelhenEntities();

        public ActionResult Content(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            File file = db.Files.Find(id);
            if (file == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            return File(file.Content, file.Contenttype);
        }

        //Indexi koostamine
        public ActionResult Index()
        {

            ViewBag.Travels = db.Travels.Select(trip => trip.DocumentID).ToList();
            //kontrollimaks, kas fail on kasutuses
            Dictionary<int, int> expensesWithDocuments = new Dictionary<int, int>();
            Dictionary<int, int> employeesWithPictures = new Dictionary<int, int>();
            foreach (TravelExpens expense in db.TravelExpenses)
            {
                if (expense.DocumentID != null && expense.TravleID != null)
                {
                    int fail = expense.DocumentID ?? -1;
                    int id = expense.TravleID ?? -1;
                    expensesWithDocuments.Add(fail, id);
                }
            }
            foreach (Person employee in db.Persons)
            {
                if (employee.PictureID != null)
                {
                    int fail = employee.PictureID ?? -1;
                    int id = employee.PersonID;
                    employeesWithPictures.Add(fail, id);
                }
            }
            ViewBag.TravelExpenseIDs = expensesWithDocuments;
            ViewBag.EmployeeIDs = employeesWithPictures;

            return View(db.Files.ToList());
        }


        // GET: Files/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            File file = db.Files.Find(id);
            if (file == null)
            {
                return HttpNotFound();
            }
            return View(file);
        }

        // GET: Files/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FileID")] File fail,HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {

                    string[] filenames = file.FileName.Split('\\');

                    fail.Filename = filenames[filenames.Length-1];

                    {
                        string[] filetyps = file.FileName.Split('.');
                        if (filetyps.Length < 2) fail.Filetype = "xxx";
                        else fail.Filetype = filetyps[filetyps.Length - 1];
                    }
                    fail.Contenttype = file.ContentType;

                    if (file.ContentLength > 0)
                    {
                        using (BinaryReader br = new BinaryReader(file.InputStream))
                        {
                            byte[] buff = br.ReadBytes(file.ContentLength);
                            fail.Content = buff;
                        }
                        db.Files.Add(fail);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
            }

            return View(file);
        }


        // GET: Files/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            File file = db.Files.Find(id);
            if (file == null)
            {
                return HttpNotFound();
            }
            return View(file);
        }

        // POST: Files/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "FileID,Filename,Filetype,Contenttype,Content")] File file)
        {
            if (ModelState.IsValid)
            {
                db.Entry(file).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(file);
        }

        // GET: Files/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            File file = db.Files.Find(id);
            if (file == null)
            {
                return HttpNotFound();
            }
            return View(file);
        }

        // POST: Files/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            File file = db.Files.Find(id);
            db.Files.Remove(file);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TravelHen_Auth_Sln/TravelHen_Auth/Controllers/TravelExpensController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TravelHen_Auth;
using System.IO;


namespace TravelHen_Auth.Controllers
{
    [Authorize]
    public class TravelExpensController : Controller
    {
        private travelhenEntities db = new travelhenEntities();
        public static int TravelID;

        // GET: TravelExpens
        public ActionResult Index()
        {
            var travelExpenses = db.TravelExpenses.Include(t => t.Expens).Include(t => t.Travel);
            return View(travelExpenses.ToList());
        }

        // GET: TravelExpens/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TravelExpens travelExpens = db.TravelExpenses.Find(id);
            if (travelExpens == null)
            {
                return HttpNotFound();
            }
            return View(travelExpens);
        }

        // GET: TravelExpens/Create
        public ActionResult Create(int? id)
        {
            ViewBag.ExpenseID = new SelectList(db.Expenses, "ExpenseID", "ExpenseName");
            ViewBag.TravleID = new SelectList(db.Travels, "TravelID", "TravelID");
            TravelID = int.Parse(id.ToString());
            return View();
        }

        // POST: TravelExpens/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TravelexpenseID,TravleID,ExpenseID,Duration,Cost,Confirmed,DocumentID")] TravelExpens travelExpens, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                db.TravelExpenses.Add(travelExpens);
                if (!decimal.TryParse(travelExpens.Cost.ToString(), out decimal cost))
                {
                    ViewBag.ErrorMessageCost = "The cost must be a decimal.";
                    return View(travelExpens);
                }

                travelExpens.TravleID = TravelID;
                db.SaveChanges();

                //failide lisamine
                if (file != null)
                    if (file.ContentLength > 0)
                    {
                        string[] filenames = file.FileName.Split('\\');
                        File loodavFail = new File();
                        loodavFail.Filename = filenames[filenames.Length - 1];
                        {
                            string[] filetyps = file.FileName.Split('.');
                            if (filetyps.Length < 2) loodavFail.Filetype = "xxx";
                            else loodavFail.Filetype = filetyps[filetyps.Length - 1];
                        }
                        loodavFail.Contenttype = file.ContentType;

                        if (file.ContentLength > 0)
                        {
                            using (BinaryReader br = new BinaryReader(file.InputStream))
                            {
                                byte[] buff = br.ReadBytes(file.ContentLength);
                                loodavFail.Content = buff;
                            }

                            db.Files.Add(loodavFail);
                            db.SaveChanges();

                            travelExpens.DocumentID = loodavFail.FileID;
                            db.SaveChanges();
                        }
                    }
                return RedirectToAction("../Travels/Index");
            }

            ViewBag.ExpenseID = new SelectList(db.Expenses, "ExpenseID", "ExpenseName", travelExpens.ExpenseID);
            ViewBag.TravleID = new SelectList(db.Travels, "TravelID", "TravelID", travelExpens.TravleID);
            return View(travelExpens);
        }

        // GET: TravelExpens/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TravelExpens travelExpens = db.TravelExpenses.Find(id);
            if (travelExpens == null)
            {
                return HttpNotFound();
            }
            ViewBag.ExpenseID = new SelectList(db.Expenses, "ExpenseID", "ExpenseName", travelExpens.ExpenseID);
            ViewBag.TravleID = new SelectList(db.Travels, "TravelID", "Place", travelExpens.TravleID);
            return View(travelExpens);
        }

        // POST: TravelExpens/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TravelexpenseID,TravleID,ExpenseID,Duration,Cost,Confirmed,DocumentID")] TravelExpens travelExpens, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                db.Entry(travelExpens).State = EntityState.Modified;
                if (!decimal.TryParse(travelExpens.Cost.ToString(), out decimal cost))
                {
                    ViewBag.ErrorMessageCost = "The cost must be a decimal.";
                    return View(travelExpens);
                }
                db.SaveChanges();
                //faili lisamine
                if (file != null)
                    if (file.ContentLength > 0)
                    {
                        string[] filenames = file.FileName.Split('\\');
                        File f = new File();
                        f.Filename = filenames[filenames.Length - 1];

                        //if (f.Filetype?.Trim() == "")
                        {
                            string[] filetyps = file.FileName.Split('.');
                            if (filetyps.Length < 2) f.Filetype = "xxx";
                            else f.Filetype = filetyps[filetyps.Length - 1];
                        }
                        f.Contenttype = file.ContentType;

                        if (file.ContentLength > 0)
                        {
                            using (BinaryReader br = new BinaryReader(file.InputStream))
                            {
                                byte[] buff = br.ReadBytes(file.ContentLength);
                                f.Content = buff;
                            }

                            db.Files.Add(f);
                            db.SaveChanges();

                            travelExpens.DocumentID = f.FileID;
                            db.SaveChanges();
                        }
                    }

                return RedirectToAction("../Travels/Index");
            }


            ViewBag.ExpenseID = new SelectList(db.Expenses, "ExpenseID", "ExpenseName", travelExpens.ExpenseID);
            ViewBag.TravleID = new SelectList(db.Travels, "TravelID", "Place", travelExpens.TravleID);
            return View(travelExpens);
        }

        // GET: TravelExpens/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TravelExpens travelExpens = db.TravelExpenses.Find(id);
            if (travelExpens == null)
            {
                return HttpNotFound();
            }
            return View(travelExpens);
        }

        // POST: TravelExpens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TravelExpens travelExpens = db.TravelExpenses.Find(id);
            if (travelExpens.File != null)
            {
                File file = travelExpens.File;
                db.Files.Remove(file);
            }
            db.TravelExpenses.Remove(travelExpens);
            db.SaveChanges();
            return RedirectToAction("../Travels/Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }




        // GET: TravelExpens/SelectFromDB/5
        public ActionResult SelectFromDB(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TravelExpens travelExpens = db.TravelExpenses.Find(id);
            if (travelExpens == null)
            {
                return HttpNotFound();
            }
            ViewBag.ExpenseID = new SelectList(db.Expenses, "ExpenseID", "ExpenseName", travelExpens.ExpenseID);
            ViewBag.TravleID = new SelectList(db.Travels, "TravelID", "Place", travelExpens.TravleID);

            //leian kasutamata failid
            Dictionary<int, int> expensesWithDocuments = new Dictionary<int, int>();
            Dictionary<int, int> employeesWithPictures = new Dictionary<int, int>();
            List<File> unusedFiles = new List<File>();
            foreach (TravelExpens expense in db.TravelExpenses)
            {
                if (expense.DocumentID != null && expense.TravleID != null)
                {
                    int fail = expense.DocumentID ?? -1;
                    int tid = expense.TravleID ?? -1;
                    expensesWithDocuments.Add(fail, tid);
                }
            }
            foreach (Person employee in db.Persons)
            {
                if (employee.PictureID != null)
                {
                    int fail = employee.PictureID ?? -1;
                    int pid = employee.PersonID;
                    employeesWithPictures.Add(fail, pid);

TravelHen_Auth_Sln/TravelHen_Auth/Views/TravelExpens/BackToTravelDetails.cshtml
@model TravelHen_Auth.TravelExpens
@Html.ActionLink("Back to Details", $"../Travels/Details/{Model.TravleID}", null, new { @class = "fancybutton fancybutton-long" })

TravelHen_Auth_Sln/TravelHen_Auth/Views/TravelExpens/Create.cshtml
@model TravelHen_Auth.TravelExpens

@{
    ViewBag.Title = "Create";
}

<h2>Add travel expense</h2>

@using (Html.BeginForm(Html.BeginForm(
    "Create",
    "TravelExpens",
    FormMethod.Post,
    new { enctype = "multipart/form-data" })))

{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">

            <div class="col-md-10">
                @ViewBag.TravelsIDInfo
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpenseID, "Expense Type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ExpenseID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ExpenseID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
                <span class="text-danger">@ViewBag.ErrorMessageCost</span>
            </div>
        </div>

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.Confirmed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Confirmed)
                    @Html.ValidationMessageFor(model => model.Confirmed, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.File, "Attach file", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="file" name="file" class="btn btn-default" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-travelhen" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Travels", $"../Travels", null, new { @class = "fancybutton fancybutton-long" })
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jquery")
    <script>

        function readURL(input) {

            if (input.files && input.files[0]) {
                $("#file").change(function () {
                    readURL(this);
                });

    </script>
}

TravelHen_Auth_Sln/TravelHen_Auth/Views/TravelExpens/Details.cshtml
@model TravelHen_Auth.TravelExpens

@{
    ViewBag.Title = "Details";
}

<h2>Travel Expense Details</h2>

@if (Model.Travel.State == null || Model.Travel.State == "d")
{
    <div class="row">
        <h4>
            @Html.ActionLink("Edit", "Edit", new { id = Model.TravelexpenseID }, new { @class = "fancybutton" })
        </h4>
    </div>

}
<hr />

<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.Duration)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Duration)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.Cost)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Cost)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.Confirmed)
    </dt>

    <dd>
        @if (Model.Confirmed == true)
        {
            <span class="okthing">Reimbursement confirmed by Accountant</span>
        }
        else
        {
            <span class="notokthing">Reimbursement not confirmed by Accountant</span>
        }
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.Expens.ExpenseName)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Expens.ExpenseName)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.Travel.Place)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Travel.Place)
    </dd>
    <dt>
        Attached files
    </dt>
    @if (Model.File == null)
    {
        <dd>
            <p><b>No file attached</b><br /></p>
        </dd>
    }
    else
    {
        <dd>
            <a href='@Url.Action("Content", "Files", new { id=Model.DocumentID })' target="_blank">
                <img id="pilt" src='@Url.Action("Content", "Files", new { id=Model.DocumentID })' class="dynamicImage img-rounded" />
            </a>
        </dd>
    }

</dl>

<p>
    @Html.Partial("BackToTravelDetails")
</p>

TravelHen_Auth_Sln/TravelHen_Auth/Views/TravelExpens/Edit.cshtml
@model TravelHen_Auth.TravelExpens

@{
    ViewBag.Title = "Edit";
}

<h2>Edit travel expense</h2>

@if (Model.Travel.State == null || Model.Travel.State == "d")
{

    using (Html.BeginForm(Html.BeginForm(
        "Edit",
        "TravelExpens",
        FormMethod.Post,
        new { enctype = "multipart/form-data" })))

    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.TravelexpenseID)

            <div class="row">
                <div class="col-md-6">

                    <div class="form-group" hidden>
                        @Html.LabelFor(model => model.TravleID, "TravleID", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("TravleID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.TravleID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ExpenseID, "Expense type", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("ExpenseID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.ExpenseID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
                            <span class="text-danger">@ViewBag.ErrorMessageCost</span>
                        </div>
                    </div>

                    @if (TravelHen_Auth.Person.GetByEmail(User.Identity.Name).IsInRole("Buchhalter") || TravelHen_Auth.Person.GetByEmail(User.Identity.Name).IsInRole("Admin"))
                    {
                        <div class="form-group">
                            @Html.LabelFor(model => model.Confirmed, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Confirmed, "ConfirmDropdown")
                                @Html.ValidationMessageFor(model => model.Confirmed, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    }
                </div>

                <div class="col-md-6">

                    <div class="form-group">
                        <div class="col-md-10">
                            @*@Html.LabelFor(model => model.File, "Attached photo", htmlAttributes: new { @class = "control-label col-md-2" })*@
                            <p><b>Attached file</b></p>
                        </div>
                    </div>

                    @if (Model.File == null)
                    {


                        <div class="form-group">
                            <input type="file" id="file" name="file" class="btn btn-default" />
                        </div>
                    }
                    else
                    {
                        <div class="form-group">
                            <a href='@Url.Action("Content", "Files", new { id = Model.DocumentID })' target="_blank">
                                <img id="pilt" src='@Url.Action("Content", "Files", new { id = Model.DocumentID })' class="dynamicImage img-rounded" />
                            </a>
                        </div>
                        <div hidden>
                            @Html.EditorFor(model => model.DocumentID, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                            @Html.ValidationMessageFor(model => model.File, "", new { @class = "text-danger" })
                        </div>
                    }

                    <div>
                        @Html.ActionLink("Select from DB", "SelectFromDB", new { id = Model.TravelexpenseID }, new { @class = "fancybutton fancybutton-long" })
                    </div>
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-travelhen" />
                </div>
            </div>
        </div>
    }
}

<div>
    @Html.Partial("BackToTravelDetails")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jquery")
    <script>

        function readURL(input) {

            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#pilt').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#file").change(function () {
            readURL(this);
        });

    </script>
}

TravelHen_Auth_Sln/TravelHen_Auth/Views/TravelExpens/SelectFromDB.cshtml
@model TravelHen_Auth.TravelExpens

@{
    ViewBag.Title = "Edit";
}
@if (Model.Travel.State != null || Model.Travel.State != "d")
{
    <h2>Select document for travel expense from database</h2>


    <div class="row">
        <div class="col-md-4">

            <div class="form-group">
                <div class="col-md-10">
                    <p><b>Attached file</b></p>
                </div>
            </div>

            @if (Model.File != null)
            {
                <div class="row">
                    <div class="col-md-3">
                        <a href='@Url.Action("Content", "Files", new { id=Model.DocumentID })' target="_blank">
                            <img src='@Url.Action("Content", "Files", new { id=Model.DocumentID })' class="dynamicImage img-rounded" />
                        </a>
                    </div>
                    <div class="col-lg-2" hidden>
                        @Html.EditorFor(model => model.DocumentID, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.File, "", new { @class = "text-danger" })
                    </div>
                </div>
            }
            else
            {
                <p>No file attached</p>
            }

        </div>
    </div>
    <p></p>

    <table class="table travelhen_table">
        <thead>
            <tr>
                <th>
                    Filename
                </th>
                <th>
                    Filetype
                </th>
                <th>
                    Image preview
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @if (ViewBag.UnusedFiles != null)
            {
                foreach (var fail in ViewBag.UnusedFiles)
                {
                    <tr>
                        <td>
                            @fail.Filename
                        </td>
                        <td>
                            @fail.Filetype
                        </td>
                        <td>
                            <a href='@Url.Action("Content", "Files", new { id = fail.FileID })' target="_blank">
                                <img src='@Url.Action("Content", "Files", new { id = fail.FileID })' class="dynamicImage img-rounded" />
                            </a>
                        </td>
                        <td>
                            @using (Html.BeginForm("SelectFromDB", "TravelExpens", new { id = Model.TravelexpenseID }))
                            {
                                <button type="submit" name="button" value=@fail.FileID class="btn btn-travelhen">Select File</button>
                            }
                            @{Html.EndForm();}
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="4">
                        <span>No files to choose from</span>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}


<div>
    @Html.ActionLink("Back to Details", $"/TravelExpens/Details/{Model.TravelexpenseID}", null, new { @class = "fancybutton fancybutton-long" })
</div>