TravelHen_Auth_Sln/TravelHen_Auth/Controllers/GalleryAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelHen_Auth.Models;
using System.IO;



namespace TravelHen_Auth.Controllers
{
    public class GalleryAdminController : Controller
    {
        // GET: GalleryAdmin
        public ActionResult Index()
        {
            return View();
        }

       
        public ActionResult Create()
        {
            ImageEditorViewModel vm = new ImageEditorViewModel();

            ViewBag.Action = "Create";
            return PartialView(vm);
        }
        [HttpPost]
        public ActionResult Create(ImageEditorViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    travelhenEntities db = new travelhenEntities();
                    var fileModel = WebFileViewModel.getEntityModel(model.FileImage);
                    db.WebFiles.Add(fileModel);
                    db.SaveChanges();

                    var entity = ImageEditorViewModel.getEntityModel(model);
                    entity.WebImageId = fileModel.Id;

                    entity.OrderNo = db.Galleries.Count() > 0 ? db.Galleries.Max(x => x.OrderNo) + 1 : 1;
                    db.Galleries.Add(entity);
                    db.SaveChanges();

                    //return Json(new { success = true, Caption = model.Caption });
                    return RedirectToAction("Index");
                }
                return Json(new { success = false, ValdiationMessage = "Please check validation message" });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, ExceptionMessage = "Some error here" });
            }
            
        }
        public ActionResult _List()
        {
            travelhenEntities db = new travelhenEntities();

            var list = db.Galleries.OrderBy(x => x.OrderNo)
                .Select(x => new ImageList
                {
                                                Id = x.Id,
                                                IsActive = x.IsActive,
                                                OrderNo = x.OrderNo,
                                                WebImageId = x.WebImageId,
                                                Title = x.Title
                }).ToList();
            return PartialView(list);
        }
        [HttpPost]
        public JsonResult ChangeActive(int Id, bool status)
        {
            travelhenEntities db = new travelhenEntities();
            var entity = db.Galleries.Find(Id);
            entity.IsActive = status;
            db.SaveChanges();

            return Json(entity.Title);
        }
    }
}

TravelHen_Auth_Sln/TravelHen_Auth/Views/GalleryAdmin/Create.cshtml
@model TravelHen_Auth.Models.ImageEditorViewModel

@using (Html.BeginForm("Create", "GalleryAdmin", FormMethod.Post, new { enctype = "multipart/form-data", Id = "frmAddImage" }))
{
    <div class="form-horizontal">
        <h4>Add Image Here</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Caption, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Caption, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Caption, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-2">
                <label class="pull-right">  Image:</label>
            </div>
            <div class="col-md-9">
                @Html.TextBoxFor(m => m.FileImage, new { type = "file" })
                @Html.ValidationMessageFor(model => model.FileImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="btnAddImage" value="Create" class="btn btn-primary" />
            </div>

        </div>
    </div>
}



@Scripts.Render("~/bundles/jqueryval")

<script type="text/javascript">

    $(function () {
        $("#btnAddImage").on("click", function (e) {
            var $form = $("#frmAddImage");
            $form.validate();
            if (!$form.valid()) {
                return false;
            }

            e.preventDefault();
            var formData = new FormData();
            var data = $form.find(':input[name]:not(:disabled)').filter(':not(:checkbox), :checked').map(function () {
                var input = $(this);

                if (input.attr('type') == "file") {

                    formData.append(input.attr('name'), input[0].files[0]);
                    return {
                        name: input.attr('name'),
                        value: input[0].files[0]
                    };
                } else {
                    formData.append(input.attr('name'), input.val());
                    return {
                        name: input.attr('name'),
                        value: input.val()
                    };
                }
            }).get();

            $.ajax({
                url: '/GalleryAdmin/Create',
                data: formData,
                type: "POST",
                contentType: false,
                processData: false,
                success: function (data, textStatus, jqXHR) {
                    if (data.success == true) {
                        $("#successmessage").html(data.Caption + " has been added successfully").show().delay(5000).fadeOut();
                        $("#ListPanel").load($("#ListPanel").data("url"));
                        $("#ImagePanel").load($("#ImagePanel").data("url"));
                        return true;
                    }
                    if (data.ExceptionMessage) {
                        $("#errormessage").html(data.ExceptionMessage).show().delay(5000).fadeOut();
                        return false;
                    }
                    if (data.ValidationMessage) {
                        $("#errormessage").html(data.ExceptionMessage).show().delay(5000).fadeOut();
                        return false;
                    }
                    return false;
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    $("#errormessage").html(textStatus).show().delay(5000).fadeOut();
                },
                complete: function (jqXHR, textStatus) {
                }
            });

        });
    });
</script>

TravelHen_Auth_Sln/TravelHen_Auth/Views/GalleryAdmin/Index.cshtml
@{
    ViewBag.Title = "Gallery Admin";
}

<h2>Gallery Admin</h2>
<div id="ImagePanel" data-url="@Url.Action("Create")">
    @Html.Action("Create")
</div>
<div class="row"´>
    <div class="col-md-offset-2 col-mod-10">
       <div class="alert alert-danger" style="display:none" role="alert" id="errormessage"></div>
        <div class="alert alert-success" style="display:none" role="alert" id="successmessage"></div>
    </div>
</div>
<hr />
<div id="ListPanel" data-url="@Url.Action("_List")">
        @Html.Action("_List")
</div>

TravelHen_Auth_Sln/TravelHen_Auth/Views/GalleryAdmin/_List.cshtml
@model IEnumerable<TravelHen_Auth.Models.ImageList>

<ul style="list-style:none; " class="row">
    @foreach (var item in Model)
        {
        <li class="col-md-3">
            <br />
            <img class="img" src="@Url.Action("GetImage", "DownloadFile", new { Area = "", Id = item.WebImageId, t = 2 })"
                 style="width:100%;height:180px;" />
            <br />
            <label>@item.Title</label>
            <br />
            <br />
        </li>
          }
        
</ul>